sudo: required
language: generic
services:
  - docker

after-success:
  - docker build -t chechandres/multi-client ./client
  - docker build -t chechandres/multi-nginx ./nginx
  - docker build -t chechandres/multi-server ./server
  - docker build -t chechandres/multi-worker ./worker
  # Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push chechandres/multi-client
  - docker push chechandres/multi-nginx
  - docker push chechandres/multi-server
  - docker push chechandres/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-065326203721'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
